name: Update Snake Animation

on:
  schedule:
    - cron: '0 0 * * *' # Set the schedule as per your preference, e.g., every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generate Snake Animation
        run: npx github-readme-stats generate-snake --user kartik2433 --color green --output README.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
